server:
  servlet:
    context-path: /api
  error:
    include-exception: true
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/choo_db?serverTimezone=UTC
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-on-validation-error: true
